### ISSUE TITLE
[UI] [EPIC] Ensure Graph Explorer follow responsive web design principles

### ISSUE THREAD

**Issue by RabebOthmani** [microsoftgraph/microsoft-graph-explorer-v4#1416]
Stories for the epic in order  of priority: 

- [ ] https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1412
- [ ] https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1414
- [ ] https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1411  
- [ ] https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1413
- [ ] https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/1415

**Comment by adhiambovivian** [comment]
@RabebOthmani  we need to define responsive design baseline requirements to guide the implementation details:

- Browser experience: Browser target baselines 
- If GE should be responsive on tablet/ mobile view
- Responsiveness for different screen sizes, resolutions, different browsers, & Zoom in & Zoom out support

**Comment by Onokaev** [comment]
This was completed in a recently closed milestone
