### ISSUE TITLE
Add support for feature flags

### ISSUE THREAD

**Issue by thewahome** [microsoftgraph/microsoft-graph-explorer-v4#1569]
**Is your feature request related to a problem? Please describe.**
To have a chance to preview new features to a limited set of users, or have the chance to remove a feature from public use, we should use feature flags.

For instance, we can release the header in preview so that we receive feedback about it. Or have two headers and show each to different users. Similar case for resource explorer and other major features that are in development.

**Describe the solution you'd like**
Connect the configurations to azure so that we can turn things on and off. 

**Describe alternatives you've considered**

**Additional context**

**Tasks include**
Breaking this into smaller tasks

- [x] Read the Azure Experimentation Platform documentation and gain knowledge about A/B testing, control groups, experiment groups, success metrics, and statistical analysis.
- [x] Set up an experimentation service and create a workspace
- [x] Design and define a sample experiment (create a hypothesis and define the variations, success metrics to measure, and traffic parameters)
- [x] Integrate Azure Experimentation Platform on GE
- [ ] Go through ExP [data contract](https://eng.ms/docs/products/experimentation-platform/docs/datasources/datacontract) and set up necessary telemetry collection on GE  
- [ ] Set up data source on the Azure Experimentation Platform
- [ ] Metrics authoring ([create new metric sets](https://eng.ms/docs/products/experimentation-platform/docs/metricauth/createnewmetricset), [define metrics](https://eng.ms/docs/products/experimentation-platform/docs/metricauth/definenewmetrics), [define segments](https://eng.ms/docs/products/experimentation-platform/docs/metricauth/definesegment) in metric sets and [publish changes to production](https://eng.ms/docs/products/experimentation-platform/docs/metricauth/createeditdeletepublishdrafts))
- [ ] Generate [scorecards](https://eng.ms/docs/products/experimentation-platform/docs/analysis/scorecard)

**Comment by ddyett** [comment]
this is agreed work engineering will drive. moving off PM.  Blocked on understanding cost.

**Comment by gavinbarron** [comment]
@thewahome I'm in fact finding mode on this at the moment looking into what internal tooling there is which we could apply to this.
