### ISSUE TITLE
Track errors in GE v4

### ISSUE THREAD

**Issue by jobala** [microsoftgraph/microsoft-graph-explorer-v4#326]
**Is your feature request related to a problem? Please describe.**
Track errors in GE v4

**Describe the solution you'd like**
## Tasks
- [ ] Show banner for user consent - check with privacy reviewer if portal cookie consent covers our cookie.
- [ ] Incidents trigger notifications over Teams.
 
#### Error Data

- [x] Track log in errors. Triggers incident.
- [ ] Track sample request errors
- [x] Track component network request errors -- Snippets, Adaptive Cards, Permissions. Triggers incident.

**Describe alternatives you've considered**

**Additional context**

Related #325  
[AB#7526](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7526)
