### ISSUE TITLE
Add telemetry into GEv4

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v4#89]
Telemetry will help us collect data on errors that the users encounter and the requests they are querying mostly while also tracking the buttons they are clicking to ensure we are consistent on the user experience for our users.

## Tasks
- [ ] Show banner for user consent
 
#### Error Data

- [ ] Track log in errors
- [ ] Track sample request errors
- [ ] Track component network request errors

#### Feature Usage Data
Todo

 
[AB#7514](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7514)

**Comment by jobala** [comment]
Tagging @MIchaelMainer

**Comment by thewahome** [comment]
Tagging @millicentachieng because it could be related to #672
